$$rem OP2Mapper version 2.0 code generation template.
$$rem Do not edit this file unless you know what you're doing.
$$rem Changing this file may cause uncompilable code to be generated.

$$rem Default template for C++ based DLLs
$$begin
void SetupObjects()
{
	// Create OP2Mapper generated objects
	Unit x;
$$player
	if (TethysGame::NoPlayers() > $playerid)
	{
$$unit
		TethysGame::CreateUnit(x, (map_id)$mapid, LOCATION($x+31, $y-1), $playerid, (map_id)$weaponmapid, 0);
$$beacon
	TethysGame::CreateBeacon((map_id)$mapid, $x+31, $y-1, $extra1, $extra2, $extra3);
$$wall
	TethysGame::CreateWallOrTube($x+31, $y-1, $extra1, (map_id)$mapid);
$$wreck
	TethysGame::CreateWreck($x+31, $y-1, (map_id)$extra1, $extra2);
$$endplayer
	}
$$end
}

