$$rem OP2Mapper version 2.0 code generation template.
$$rem Do not edit this file unless you know what you're doing.
$$rem Changing this file may cause uncompilable code to be generated.

$$rem Fully-functional DLL template
$$begin
#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <Outpost2DLL.h>
#include <OP2Helper.h>

// This mission contains everything you need for a complete LoS, except initial units
// and disasters.
// Just edit where prompted to complete your mission. Everything else is default/
// filled in by the map editor! :-)

// *** Edit this to set your level name ***
char LevelDesc[]	= "$playersusedP, LoS, '<YOUR LEVEL NAME HERE>' map.";

// *** Don't edit below here, unless you want to customize further ***
char MapName[]		= "$mapname";
char TechtreeName[]	= "MULTITEK.TXT";
SDescBlock DescBlock	= { MultiLastOneStanding, $playersused, 12, 0 };

BOOL APIENTRY DllMain(HINSTANCE hinstDLL, DWORD fdwReason, LPVOID lpvReserved)
{
	if (fdwReason == DLL_PROCESS_ATTACH) 
		DisableThreadLibraryCalls(hinstDLL);

	return TRUE;
}

int InitProc()
{
	Unit x; int i; int randList[$playersused];
$$rem Create an array which maps player numbers (from the editor)
$$rem to a random player number
	for (i = 0; i < $playersused; i++) randList[i] = i;
	RandomizeList($playersused, randList);

$$player
	if (TethysGame::NoPlayers() > $playerid)
	{
$$unit
		TethysGame::CreateUnit(x, (map_id)$mapid, LOCATION($x+31, $y-1), randList[$playerid], (map_id)$weaponmapid, 0);
$$beacon
	TethysGame::CreateBeacon((map_id)$mapid, $x+31, $y-1, $extra1, $extra2, $extra3);
$$wall
	TethysGame::CreateWallOrTube($x+31, $y-1, $extra1, (map_id)$mapid);
$$wreck
	TethysGame::CreateWreck($x+31, $y-1, (map_id)$extra1, $extra2);
$$endplayer
	}
$$end

	for (i = 0; i < TethysGame::NoPlayers(); i++)
	{
$$rem Setup the player resources and kits.
		PlayerBuildingEnum sfEnum(i, mapStructureFactory); Unit sf;
		while (sfEnum.GetNext(sf))
		{
			if (Player[i].Difficulty() < 3)
			{
				sf.SetFactoryCargo(0, mapTokamak, mapNone);
				sf.SetFactoryCargo(1, mapNursery, mapNone);
				sf.SetFactoryCargo(2, mapUniversity, mapNone);
				if (Player[i].Difficulty() < 2)
				{
					sf.SetFactoryCargo(3, mapVehicleFactory, mapNone);
					sf.SetFactoryCargo(4, mapRobotCommand, mapNone);
					sf.SetFactoryCargo(5, mapResidence, mapNone);
				}
			}
		}
		InitPlayerResources(i);
$$rem Setup the player research.
		Player[i].MarkResearchComplete(3303);
		if (Player[i].Difficulty() < 3)
		{
			Player[i].MarkResearchComplete(3305);
			Player[i].MarkResearchComplete(3304);
			if (Player[i].Difficulty() < 2) Player[i].MarkResearchComplete(3401);
		}
	}

$$rem Setup the basic mission settings like morale, day/night, etc.
	TethysGame::ForceMoraleGood(-1);
	if (TethysGame::UsesMorale()) TethysGame::FreeMoraleLevel(-1);
	TethysGame::SetDaylightEverywhere(TethysGame::UsesDayNight() == 0);
	TethysGame::SetDaylightMoves(0);
	GameMap::SetInitialLightLevel(-32);
	
	CreateLastOneStandingVictoryCondition();
	return 1;
}

void AIProc() {}
void __cdecl GetSaveRegions(struct BufferDesc &bufDesc) { bufDesc.bufferStart = 0; bufDesc.length = 0; }
int StatusProc() { return 0; }
void NoResponseToTrigger() {}

