; OP2Mapper version 2.0 gaia (non-player) object definitions file.
; objects.ctl

; Do not edit this file unless you know what you're doing.
; Changing this file may cause problems with object placement or remove objects from the editor altogether.


; Each line has the following format:
; MapID,"Name",Type,ArtID,Extra1,Extra2,Extra3

; Type is a numeric value:
; 0 = beacon
; 1 = wall/tube
; 2 = wreck
; This has nothing to do with displaying or placing the units, but the code generator uses to decide which
; template element to use ($$beacon, $$wall, or $$wreck).

; Extra1..3 can be omitted as needed, and are used as the 'extra' parameters to the template elements.

; Note: Do not put extra spaces or tabs! This may cause a parse error.
; However blank lines are permissible.
; Lines beginning with ; are comments and get ignored by the parser.

; Note: You can read other files from within an existing file by using:
; INCLUDE "filename.ctl"

; Special Art IDs:
; -1 = DO NOT DRAW
; -2 = Letter T (white)
; -3 = Letters NW (cyan)
; -4 = Letters LW (cyan)
; -5 = Letters MW (cyan)
; NOTE: With the exception of -1, these only work on objects that aren't structures and don't have tubes
; (in other words, these are meant for gaia objects)


; Tubes and Walls
; extra1 = unknown(?) value (3rd parameter of CreateWallOrTube)
17,"Tube",1,-2,0
18,"Normal Wall",1,-3,0
19,"Lava Wall",1,-4,0
20,"Microbe Wall",1,-5,0


; Beacons
; extra1 = common/rare
; extra2 = yield type
; extra3 = variant type
81,"Common Beacon 1",0,1749,0,2,-1
81,"Common Beacon 2",0,1750,0,1,-1
81,"Common Beacon 3",0,1751,0,0,-1
81,"Rare Beacon 1",0,1752,1,2,-1
81,"Rare Beacon 2",0,1753,1,1,-1
81,"Rare Beacon 3",0,1754,1,0,-1
82,"Magma Vent",0,573
83,"Fumarole",0,58


; Wreckage
; extra1 = Tech ID to give
; extra2 = (BOOL) can be seen without needing a scout?
84,"Tiger Speed Mod Wreckage",2,1856,11999,1

; Do not remove this line. It's a workaround for a bug that exists in almost every text parser.