; OP2Mapper version 2.0 unit definitions file.
; Do not edit this file unless you know what you're doing.
; Changing this file may cause problems with unit placement or remove units from the editor altogether.


; Each line has the following format:
; MapID,"Name",Width,Height,vTubeX,hTubeY,ArtID
; Tube values are an X, Y offset from the edge of the bulldozed border.
; If unit is a structure without tubes: Omit the vTubeX and vTubeY params.
; If unit is a vehicle: Omit the Width, Height, vTubeX, and vTubeY params.

; Note: Do not put extra spaces or tabs! This may cause a parse error.
; However blank lines are permissible.
; Lines beginning with ; are comments and get ignored by the parser.

; Note: You can read other files from within an existing file by using:
; INCLUDE "filename.ctl"


; Structures
28,"Command Center",3,2,2,2,70
58,"Tokamak",2,2,76
29,"MHD Generator",2,2,413
44,"Geothermal Plant",2,1,426
36,"Solar Power Array",3,2,80
47,"Structure Factory",4,3,3,2,72

; **TODO**: figure out something better for the guard post.
; There is no art for a guard post without a turret on it, so we had to use something that looks a bit like
; an oversized ESG mine.
23,"Guard Post",1,1,1,1,441

54,"Common Ore Smelter",4,3,3,2,79
25,"Common Storage",1,2,1,2,69
50,"Advanced Lab",3,3,2,2,153
49,"Standard Lab",3,2,2,2,141
33,"Basic Lab",2,2,2,2,74
56,"Rare Ore Smelter",4,3,3,2,369
26,"Rare Storage",1,2,1,2,390
48,"Vehicle Factory",4,3,3,2,75
38,"University",2,2,2,2,147
35,"Nursery",2,2,2,2,595
39,"Agridome",3,2,2,2,142
31,"Robot Command Center",2,2,2,2,78
55,"Spaceport",5,4,3,3,425
34,"Medical Center",2,2,2,2,145
45,"Arachnid Factory",2,2,2,2,158
40,"DIRT",3,2,2,2,71
41,"Garage",3,2,2,2,2038
57,"GORF",3,2,2,2,382
53,"Advanced Residence",3,3,2,2,152
30,"Residence",2,2,2,2,77
52,"Reinforced Residence",3,2,2,2,171
51,"Observatory",2,2,2,2,398
43,"Meteor Defense",2,2,2,2,567
37,"Recreation Facility",2,2,2,2,146
46,"Consumer Goods Factory",3,3,2,2,365
27,"Forum",2,2,2,2,159
32,"Trade Center",2,2,2,2,386
24,"Light Tower",1,1,155
42,"Magma Well",2,1,1336
21,"Common Ore Mine",2,1,104
22,"Rare Ore Mine",2,1,405


; Vehicles
10,"GeoCon",1154
9,"Robo-Miner",1170
7,"Tiger",231
1,"Cargo Truck",8
6,"Panther",239
5,"Lynx",1202
2,"ConVec",287
15,"Earthworker",1811
14,"Repair Vehicle",1130
12,"Robo-Dozer",0
13,"Evacuation Transport",303
8,"Robo-Surveyor",247
11,"Scout",442
4,"Scorpion",1649
3,"Spider",1633

; Do not remove this line. It's a workaround for a bug that exists in almost every text parser.