; OP2Mapper version 2.0 weapon definitions file.
; weapons.ctl

; Do not edit this file unless you know what you're doing.
; Changing this file may cause problems with weapon placement or remove weapons from the editor altogether.


; Each line has the following format:
; MapID,"Name",ArtID

; Note: Do not put extra spaces or tabs! This may cause a parse error.
; However blank lines are permissible.
; Lines beginning with ; are comments and get ignored by the parser.

; Note: You can read other files from within an existing file by using:
; INCLUDE "filename.ctl"

; To define units that have a turret, use the following:
; HASTURRET mapID
; Where mapID is the mapID defined in units.ctl.


; Units with Turrets
; Guard Post
HASTURRET 23
; Tiger
HASTURRET 7
; Panther
HASTURRET 6
; Lynx
HASTURRET 5


; Weapons
61,"Laser",1525
62,"Microwave",1493
71,"StickyFoam",1427
63,"Rail Gun",1363
60,"EMP",1270
64,"RPG",1395
67,"Starflare",1623
70,"ESG",1461
68,"Supernova",1342
59,"Acid Cloud",1589
72,"Thor's Hammer",1557

; Do not remove this line. It's a workaround for a bug that exists in almost every text parser.